/*
 * Tagerator is Copyright 2011 by Jeremy Brooks
 *
 * This file is part of Tagerator.
 *
 *  Tagerator is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Tagerator is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 */
package net.jeremybrooks.tagerator;

import java.io.FileReader;
import net.whirljack.common.util.IOUtil;
import org.apache.log4j.Logger;

/**
 *
 * @author jeremyb
 */
public class TagWindow extends javax.swing.JFrame {

    private Logger logger = Logger.getLogger(TagWindow.class);
    
    /** Creates new form TagWindow */
    public TagWindow() {
        initComponents();

	FileReader in = null;
	char[] buf = new char[1024];
	int pos = 0;
	try {
	    in = new FileReader(Main.tagCloudFile);
	    while ((in.read(buf)) != -1) {
		this.txtTags.append(new String(buf));
	    }
	    
	    this.txtTags.setCaretPosition(0);
	} catch (Exception e) {
	    logger.error("Could not show tags.", e);
	} finally {
	    IOUtil.close(in);
	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTags = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Tags");

        txtTags.setColumns(20);
        txtTags.setEditable(false);
        txtTags.setLineWrap(true);
        txtTags.setRows(5);
        txtTags.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtTags);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTags;
    // End of variables declaration//GEN-END:variables

}
